### ISSUE TITLE
Required Ruby Version is unclear

### ISSUE THREAD

**Issue by cortfr** [yoshoku/rumale#43]
I tried installing with Ruby 2.3, but I ran into this error while building rumale-tree-0.27:

extconf.rb:26:in `<main>': undefined method `match?' for "aarch64-linux":String (NoMethodError)

That suggests Ruby 2.4 is the minimum version.  

https://rubygems.org/gems/rumale doesn't provide much information as well.   Can you help clarify which version of Ruby you are targeting?

Thank you!

**Comment by yoshoku** [comment]
Rumale supports versions that have not reached EOL: https://github.com/yoshoku/rumale/blob/v0.28.0/.github/workflows/main.yml#L20
However, since there may be some machine learning algorithm in Rumale that will work with versions of Ruby that have reached EOL, I do not specify the version in the gemspec file: https://github.com/yoshoku/rumale/blob/main/.rubocop.yml#L12-L13
